version: '3.8'
services:
  jenkins_docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    command: --storage-driver=overlay2
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - 2376:2376
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
    networks:
      jenkins-network:
          aliases:
            - docker

  jenkins:
    build: .
    container_name: jenkins-blueocean
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
    networks:
      - jenkins-network
    
networks:
  jenkins-network:
    external: false
    name: jenkins-network
        